from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class ProductionRouteDecision:
    intent: str
    action: str
    reason: str
    evidence: tuple[str, ...] = field(default_factory=tuple)
    protected_inputs: tuple[str, ...] = field(default_factory=tuple)


@dataclass(frozen=True)
class ProductionSituation:
    chapter_number: int
    chapter_status: str
    has_brief: bool
    latest_version_status: str
    latest_quality_passed: bool | None
    publish_action: str = ""
    publish_reason: str = ""
    draft_queue_status: str = ""
    draft_queue_id: int | None = None
    revision_queue_status: str = ""
    revision_queue_id: int | None = None
    has_revision_brief: bool = False
    has_sample_adoption: bool = False
    has_continuity_context: bool = False
    budget_blocker: str = ""
    trend_blocker: str = ""
    should_generate_rebuild_candidates: bool = False
    reading_assessment_requires_revision: bool = False
    protected_review_contract_passed: bool = False
    feedback_marker_without_quality: bool = False
    revision_matches_quality_or_feedback: bool = False
    story_clean_revision_brief: bool = False
    # Sprint 2 Phase E.3: a revision brief auto-generated by the reading-
    # assessment contract carries markers like `reading_assessment_contract`
    # / `reading_assessment_auto_quality#`. Previously such a brief could
    # only route to revise via `protected_review_contract_passed` (requires
    # quality.passed=True) or `reading_assessment_requires_revision(quality)`
    # (requires the current QR to demand more RA revision). When
    # quality.passed=False AND the QR does not demand further RA, none of
    # the revision branches match and the orchestrator fell through to
    # create_revision_brief every round (Book2 Ch4 accumulated 645 briefs).
    # This flag routes RA-contract briefs to revise_chapter regardless of
    # the QR's flags — the contract itself is the routing signal.
    has_reading_assessment_contract_brief: bool = False
    # Sprint 2 Phase E.3 (exhaustion escalation): when linear revise + N
    # rebuild-candidate batches (>=2) have all failed to produce a passing
    # version, force accept_early_stop on the best-scoring version and log
    # a QA backlog entry. Prevents the "no terminal state" dead loop where
    # Ch4 kept spawning rebuild batches without converging (6+ batches, 31+
    # versions, 645 briefs). See
    # scripts/rebuild_exhaustion_escalation_regression.py.
    rebuild_and_revision_exhausted: bool = False
    exhausted_best_version_number: int | None = None
    exhausted_best_score: int = 0
    exhausted_rebuild_batch_count: int = 0
    strategy_action: str = ""
    strategy_intent: str = ""
    strategy_reason: str = ""
    strategy_category: str = ""
    strategy_confidence: int = 0
    strategy_evidence: tuple[str, ...] = field(default_factory=tuple)
    # ---- early-stop signals (phase 2) -----------------------------------
    # These are populated by planning.py from evaluate_early_stop() over the
    # chapter's version history. When ``early_stop_should_stop`` is True the
    # orchestrator preempts every ``revise_chapter`` branch and routes to
    # ``accept_early_stop`` (best score >= threshold) or
    # ``escalate_early_stop_ceiling`` (max_versions hit without a pass).
    early_stop_should_stop: bool = False
    early_stop_reason: str = ""
    early_stop_best_version: int | None = None
    early_stop_best_score: int | None = None
    early_stop_triggered_rules: tuple[str, ...] = field(default_factory=tuple)


def decide_production_route(situation: ProductionSituation) -> ProductionRouteDecision:
    s = situation
    evidence = _evidence(s)
    protected_inputs = _protected_inputs(s)

    if not s.has_brief:
        return ProductionRouteDecision(
            intent="repair_missing_brief",
            action="create_chapter_brief",
            reason="chapter exists but brief is missing",
            evidence=evidence,
            protected_inputs=protected_inputs,
        )
    if not s.latest_version_status or s.latest_version_status == "missing":
        if s.draft_queue_status:
            return ProductionRouteDecision(
                intent="wait_draft_queue",
                action="wait_generation_task",
                reason=f"draft generation task {s.draft_queue_id} is {s.draft_queue_status}",
                evidence=evidence,
                protected_inputs=protected_inputs,
            )
        return ProductionRouteDecision(
            intent="draft_from_brief",
            action="draft_chapter",
            reason="brief is ready and no chapter version exists",
            evidence=evidence,
            protected_inputs=protected_inputs,
        )
    if s.latest_version_status == "draft":
        return ProductionRouteDecision(
            intent="review_draft",
            action="review_chapter",
            reason="latest version is draft",
            evidence=evidence,
            protected_inputs=protected_inputs,
        )
    if s.latest_version_status == "needs_revision":
        return _decide_revision_route(s, evidence=evidence, protected_inputs=protected_inputs)
    if s.latest_version_status == "reviewed_pass":
        if s.chapter_status != "continuity_recorded":
            return ProductionRouteDecision(
                intent="record_continuity",
                action="record_chapter_continuity",
                reason="quality passed but continuity has not been recorded",
                evidence=evidence,
                protected_inputs=protected_inputs,
            )
        return ProductionRouteDecision(
            intent="approve_after_continuity",
            action="approve_chapter",
            reason="quality and continuity are complete",
            evidence=evidence,
            protected_inputs=protected_inputs,
        )
    if s.latest_version_status == "approved":
        return ProductionRouteDecision(
            intent="publish_flow",
            action=s.publish_action or "done",
            reason=s.publish_reason or "approved chapter has no pending publish action",
            evidence=evidence,
            protected_inputs=protected_inputs,
        )
    return ProductionRouteDecision(
        intent="inspect_unknown_state",
        action="inspect_manually",
        reason=f"unhandled latest version status: {s.latest_version_status}",
        evidence=evidence,
        protected_inputs=protected_inputs,
    )


def _decide_revision_route(
    s: ProductionSituation,
    *,
    evidence: tuple[str, ...],
    protected_inputs: tuple[str, ...],
) -> ProductionRouteDecision:
    # Sprint 2 Phase E.3 exhaustion escalation: MUST run before the queue-wait
    # short-circuit. Otherwise a lingering pending revision/rebuild task
    # forever blocks the exhaustion path — the very dead loop we're trying
    # to break. Exhaustion signal being True already means ≥2 rebuild
    # batches have COMPLETED, so short-circuiting on a fresh pending task
    # (spawned from the same dead loop) is what kept Ch4 stuck.
    if s.rebuild_and_revision_exhausted and s.exhausted_best_version_number is not None:
        reason = (
            f"exhaustion escalation: revise+rebuild exhausted after "
            f"{s.exhausted_rebuild_batch_count} rebuild batches; "
            f"soft-pass best v{s.exhausted_best_version_number} "
            f"score={s.exhausted_best_score} (QA backlog logged)"
        )
        return ProductionRouteDecision(
            intent="accept_early_stop_soft_pass",
            action="accept_early_stop",
            reason=reason,
            evidence=(
                *evidence,
                f"rebuild_batch_count={s.exhausted_rebuild_batch_count}",
                f"best=v{s.exhausted_best_version_number}@{s.exhausted_best_score}",
                "soft_pass=True",
                "qa_backlog=escalated",
            ),
            protected_inputs=protected_inputs,
        )
    if s.revision_queue_status:
        return ProductionRouteDecision(
            intent="wait_revision_queue",
            action="wait_generation_task",
            reason=f"revision generation task {s.revision_queue_id} is {s.revision_queue_status}",
            evidence=evidence,
            protected_inputs=protected_inputs,
        )
    # Sprint 2 P2-Ch28 fix: early-stop with an accept-worthy best version must
    # win over strategy_action overrides. Otherwise a lingering
    # ``generate_rebuild_candidates`` strategy signal keeps burning tokens
    # even after we've already produced a >=75 candidate that early-stop is
    # willing to accept. Symptom on Ch28: 31 versions, best v26 score=77
    # (early-stop says should_stop=True), planner still routed to
    # generate_rebuild_candidates because strategy_action short-circuited
    # at the top. Now: if early-stop has surfaced an accept-worthy score,
    # take it immediately.
    if s.early_stop_should_stop and s.early_stop_best_score is not None and s.early_stop_best_score >= 75:
        reason = (
            f"early-stop preempts strategy: {s.early_stop_reason}"
            if s.early_stop_reason
            else f"early-stop preempts strategy: best v{s.early_stop_best_version} score={s.early_stop_best_score}"
        )
        return ProductionRouteDecision(
            intent="accept_early_stop",
            action="accept_early_stop",
            reason=reason,
            evidence=(
                *evidence,
                f"early_stop_rules={','.join(s.early_stop_triggered_rules) or 'unknown'}",
                f"best=v{s.early_stop_best_version}@{s.early_stop_best_score}",
            ),
            protected_inputs=protected_inputs,
        )
    if s.strategy_action in {"generate_rebuild_candidates", "revision_budget_recovery", "revision_trend_recovery"}:
        return ProductionRouteDecision(
            intent=s.strategy_intent or "production_strategy_override",
            action=s.strategy_action,
            reason=s.strategy_reason or "生产策略层判定当前路径无效，自动切换下一步。",
            evidence=(*evidence, *s.strategy_evidence),
            protected_inputs=protected_inputs,
        )
    # ---------------------------------------------------------------- early-stop
    # phase 2/1b: preempt every ``revise_chapter`` branch below when the
    # early-stop policy has decided the loop should halt. Two outcomes:
    #   * best_score >= threshold  -> accept the best version we already have
    #   * ceiling hit without pass -> escalate: kick rebuild candidates
    # The strategy override above still wins because it encodes higher-order
    # signals (comparison loops, budget recovery) that the pure early-stop
    # policy can't see. Queue-in-flight also wins so we never preempt a
    # revision that's already spending tokens.
    if s.early_stop_should_stop:
        best = s.early_stop_best_score
        if best is not None and best >= 75:
            reason = (
                f"early-stop: {s.early_stop_reason}"
                if s.early_stop_reason
                else f"early-stop: best v{s.early_stop_best_version} score={best}"
            )
            return ProductionRouteDecision(
                intent="accept_early_stop",
                action="accept_early_stop",
                reason=reason,
                evidence=(
                    *evidence,
                    f"early_stop_rules={','.join(s.early_stop_triggered_rules) or 'unknown'}",
                    f"best=v{s.early_stop_best_version}@{best}",
                ),
                protected_inputs=protected_inputs,
            )
        # No passing candidate — bail out of the linear revise loop and hand
        # off to rebuild candidates. This mirrors the 'linear_revision_exhaustion'
        # strategy rule but is triggered by the token-budget layer instead of
        # score trends.
        reason = (
            f"early-stop ceiling: {s.early_stop_reason}"
            if s.early_stop_reason
            else "early-stop ceiling hit without any passing version"
        )
        return ProductionRouteDecision(
            intent="escalate_early_stop_ceiling",
            action="generate_rebuild_candidates",
            reason=reason,
            evidence=(
                *evidence,
                f"early_stop_rules={','.join(s.early_stop_triggered_rules) or 'unknown'}",
                f"best={s.early_stop_best_version}@{best}" if best is not None else "best=none",
            ),
            protected_inputs=protected_inputs,
        )
    if s.has_revision_brief and s.budget_blocker:
        return ProductionRouteDecision(
            intent="recover_revision_budget",
            action="revision_budget_recovery",
            reason=s.budget_blocker,
            evidence=evidence,
            protected_inputs=protected_inputs,
        )
    if s.trend_blocker:
        return ProductionRouteDecision(
            intent="recover_revision_trend",
            action="revision_trend_recovery",
            reason=s.trend_blocker,
            evidence=evidence,
            protected_inputs=protected_inputs,
        )
    if s.has_revision_brief and s.should_generate_rebuild_candidates:
        return ProductionRouteDecision(
            intent="generate_rebuild_candidates",
            action="generate_rebuild_candidates",
            reason="连续重建/修订未通过，改为多候选生成并自动择优，停止单稿线性烧修订。",
            evidence=evidence,
            protected_inputs=protected_inputs,
        )
    if s.has_revision_brief and s.reading_assessment_requires_revision:
        return ProductionRouteDecision(
            intent="revise_from_reading_assessment",
            action="revise_chapter",
            reason=_revision_reason(s, "阅读评估已自动生成修订合同，继续修到可读候选稿"),
            evidence=evidence,
            protected_inputs=protected_inputs,
        )
    if s.has_revision_brief and s.protected_review_contract_passed:
        return ProductionRouteDecision(
            intent="revise_protected_review_contract",
            action="revise_chapter",
            reason=_revision_reason(s, "基础质检虽通过，但主编准定稿标准未关闭当前合同，继续自动定点修订。"),
            evidence=evidence,
            protected_inputs=protected_inputs,
        )
    if s.has_revision_brief and s.feedback_marker_without_quality:
        return ProductionRouteDecision(
            intent="revise_feedback_or_recovery",
            action="revise_chapter",
            reason=_revision_reason(s, "latest version has a feedback/recovery brief and should continue revision"),
            evidence=evidence,
            protected_inputs=protected_inputs,
        )
    if s.has_revision_brief and s.revision_matches_quality_or_feedback:
        return ProductionRouteDecision(
            intent="revise_matching_contract",
            action="revise_chapter",
            reason=_revision_reason(s, "latest version needs revision and revision brief exists"),
            evidence=evidence,
            protected_inputs=protected_inputs,
        )
    if s.has_revision_brief and s.story_clean_revision_brief:
        return ProductionRouteDecision(
            intent="revise_story_clean_contract",
            action="revise_chapter",
            reason=_revision_reason(s, "latest version needs revision and clean revision brief exists"),
            evidence=evidence,
            protected_inputs=protected_inputs,
        )
    # Sprint 2 Phase E.3 (Book2 Ch4 death-loop fix): a reading-assessment
    # contract revision brief must route to revise_chapter even when
    # quality.passed=False and the current QR does not demand further RA.
    # Without this branch we fall through to create_revision_brief every
    # round and accumulate hundreds of superseded briefs. See
    # scripts/reading_assessment_contract_route_regression.py.
    if s.has_revision_brief and s.has_reading_assessment_contract_brief:
        return ProductionRouteDecision(
            intent="revise_reading_assessment_contract",
            action="revise_chapter",
            reason=_revision_reason(s, "reading_assessment_contract brief active; must revise regardless of QR flags"),
            evidence=evidence,
            protected_inputs=protected_inputs,
        )
    return ProductionRouteDecision(
        intent="create_revision_brief",
        action="create_revision_brief",
        reason="latest version failed quality needs fresh revision brief",
        evidence=evidence,
        protected_inputs=protected_inputs,
    )


def _revision_reason(s: ProductionSituation, base: str) -> str:
    details: list[str] = []
    if s.has_sample_adoption:
        details.append("已采用小样方向必须继承")
    if s.has_continuity_context:
        details.append("必须承接上一章后果")
    return base if not details else f"{base}；{'；'.join(details)}"


def _evidence(s: ProductionSituation) -> tuple[str, ...]:
    rows = [
        f"chapter_status={s.chapter_status or 'unknown'}",
        f"version_status={s.latest_version_status or 'missing'}",
    ]
    if s.latest_quality_passed is not None:
        rows.append(f"quality_passed={bool(s.latest_quality_passed)}")
    if s.budget_blocker:
        rows.append(f"budget={s.budget_blocker}")
    if s.trend_blocker:
        rows.append(f"trend={s.trend_blocker}")
    if s.strategy_category:
        rows.append(f"strategy={s.strategy_category}:{s.strategy_confidence}")
    return tuple(rows)


def _protected_inputs(s: ProductionSituation) -> tuple[str, ...]:
    rows: list[str] = []
    if s.has_sample_adoption:
        rows.append("chapter_sample_adoption")
    if s.has_continuity_context:
        rows.append("previous_chapter_continuity")
    if s.has_revision_brief:
        rows.append("active_revision_brief")
    return tuple(rows)
